//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Admin
{


    public partial class EditJob
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// txtCustomerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCustomerName;

        /// <summary>
        /// txtContactNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactNumber;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// ddlService control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlService;

        /// <summary>
        /// txtWeight control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtWeight;

        /// <summary>
        /// txtRemarks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
    }
}
