//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Admin
{


    public partial class Pricing
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// txtMinimumCharge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMinimumCharge;

        /// <summary>
        /// ddlRounding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRounding;
    }
}
