//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Admin
{


    public partial class Reports
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// txtMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMonth;

        /// <summary>
        /// txtDay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDay;

        /// <summary>
        /// btnShow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnShow;
    }
}
