//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Admin
{


    public partial class Settings
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// txtShopName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtShopName;

        /// <summary>
        /// txtSlipHeader control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSlipHeader;

        /// <summary>
        /// txtClaimFormat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClaimFormat;

        /// <summary>
        /// txtTurnaroundHours control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTurnaroundHours;

        /// <summary>
        /// txtUnclaimedDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUnclaimedDays;
    }
}
