//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Pages.Shared
{


    public partial class Customers
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// litNotice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNotice;

        /// <summary>
        /// pnlSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSearch;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// rptCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCustomers;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// lblNameError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNameError;

        /// <summary>
        /// txtContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContact;

        /// <summary>
        /// lblContactError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblContactError;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// lblEmailError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmailError;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
