//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Pages.Shared
{


    public partial class Dashboard
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// litNotice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNotice;

        /// <summary>
        /// txtFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFilter;

        /// <summary>
        /// rptColumns control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptColumns;

        /// <summary>
        /// rptClaimed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptClaimed;
    }
}
