//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Pages.Shared
{


    public partial class JobDetail
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// rptStepper control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptStepper;

        /// <summary>
        /// pnlQueued control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQueued;

        /// <summary>
        /// txtVoidReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVoidReason;

        /// <summary>
        /// pnlAdvance control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdvance;

        /// <summary>
        /// pnlInspection control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlInspection;

        /// <summary>
        /// ddlReworkStage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlReworkStage;

        /// <summary>
        /// txtReworkReason control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReworkReason;

        /// <summary>
        /// pnlReady control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlReady;

        /// <summary>
        /// pnlClosed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlClosed;

        /// <summary>
        /// rptHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHistory;

        /// <summary>
        /// rptPayments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPayments;
    }
}
