//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABATRACK.Pages.Shared
{


    public partial class NewJob
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litNav control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNav;

        /// <summary>
        /// txtSearchContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchContact;

        /// <summary>
        /// txtCustomerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCustomerName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// ddlService control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlService;

        /// <summary>
        /// txtWeight control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtWeight;

        /// <summary>
        /// txtRemarks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;

        /// <summary>
        /// txtExpectedPickup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpectedPickup;

        /// <summary>
        /// rbCash control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbCash;

        /// <summary>
        /// rbEwallet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbEwallet;

        /// <summary>
        /// txtCashReceived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCashReceived;

        /// <summary>
        /// lblPaymentError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaymentError;

        /// <summary>
        /// btnCreate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreate;
    }
}
